# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        spot_uploads:
            local:
                location: '%spot_images%'
        photo_uploads:
            local:
                location: '%photos%'
        avatar_uploads:
            local:
                location: '%avatars%'
    filesystems:
        spot_uploads:
            adapter: spot_uploads
        photo_uploads:
            adapter: photo_uploads
        avatar_uploads:
            adapter: avatar_uploads