twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        menu: '@App\Service\MenuGenerator'
        spot_service: '@App\Service\SpotService'

when@test:
    twig:
        strict_variables: true
