# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    public_dir: '%kernel.project_dir%/public'
    spot_images: '%public_dir%/images/spots'
    photos: '%public_dir%/images/photos'
    avatars: '%public_dir%/images/avatars'
    exceptions:
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: { code: 404 }
        App\Exception\SpotNotFoundException: { code: 404, hidden: false }
        App\Exception\CategoryNotFoundException: { code: 404, hidden: false }
        App\Exception\SpotAlreadyExistsException: { code: 409, hidden: false }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            App\Service\ImageUploader $spotUploader: '@image_uploader.spot'
            App\Service\ImageUploader $photoUploader: '@image_uploader.photo'
            App\Service\ImageUploader $avatarUploader: '@image_uploader.avatar'
            League\Flysystem\Filesystem $spotFilesystem: '@oneup_flysystem.spot_uploads_filesystem'
            League\Flysystem\Filesystem $photoFilesystem: '@oneup_flysystem.photo_uploads_filesystem'
            bool $isDebug: '%kernel.debug%'

    postPersist:
        class: App\Listener\SpotRatingUpdateListener
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Vote'
                method: 'updateSpotRating'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ExceptionHandler\ExceptionMappingResolver:
        arguments: ['%exceptions%']

    App\Listener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    image_uploader.spot:
        class: App\Service\ImageUploader
        arguments:
            $filesystem: '@oneup_flysystem.spot_uploads_filesystem'
            $filters:
                preview: 'spot'
                medium: 'spot'

    image_uploader.photo:
        class: App\Service\ImageUploader
        arguments:
            $filesystem: '@oneup_flysystem.photo_uploads_filesystem'
            $filters:
                preview: 'photo'
                medium: 'photo'

    image_uploader.avatar:
        class: App\Service\ImageUploader
        arguments:
            $filesystem: '@oneup_flysystem.avatar_uploads_filesystem'
            $filters:
                preview: 'avatar'